### ISSUE TITLE
Setting env variable KRD_ACTIONS as array does not work

### ISSUE THREAD

**Issue by thuydang** [electrocucaracha/krd#6]
Hi,

I want to set the variable KRD_ACTIONS and run aio.sh setup but the variable is empty when passed from bash to the bash script (ubuntu 18.04). So I need to define the variable directly in the script. The issue with array variable is described [here](https://stackoverflow.com/a/57958263/707704).

I think it would help beginners like me to update the baremetal /aio setup guide or is there any fix for the issue that I'm unaware of?

Thanks!

**Comment by electrocucaracha** [comment]
Hey @thuydang,

First of all, thanks for using this project and thanks for taking the time and report this issue (I really appreciate feedback). I need to improve the documentation, specially the information related to Bare metal deployments but in the meantime, you can use the following instructions to do the deployment,

    KRD_ACTIONS=("install_k8s")
    curl -fsSL https://raw.githubusercontent.com/electrocucaracha/krd/master/aio.sh | KRD_ACTIONS_DECLARE=$(declare -p KRD_ACTIONS) bash

I tested that instruction in the [NonPreemptingPriority demo project](https://github.com/electrocucaracha/k8s-NonPreemptingPriority-demo) and seems to be working fine.

**Comment by thuydang** [comment]
Hi @electrocucaracha,

thanks for your work and help. I could start the install_k8s but etcd has an error which I documented [here](https://jira.onap.org/browse/MULTICLOUD-821). My workaround was to bump kubespray version to 2.11.0. Do you think this change may break something? I not I will be happy to make an onap multicloud commit!

Cheer!

**Comment by electrocucaracha** [comment]
Got it, let me give you a little context. This project was created as a way to provided a Kubernetes Cluster for the ONAP Multi-Cloud plugin and later was merged in the [official repo](https://github.com/onap/multicloud-k8s/). I decided to keep this project as lab for personal projects. As result this project has evolved and diverged from the initial goal.

The sub-project that deploys a Kubernetes cluster for the ONAP Multi-cloud project was named to KUD and its source code is located [here](https://github.com/onap/multicloud-k8s/tree/master/kud).

I don't think that upgrading the kubespray version to `2.11.0` fix the issue because according to its [official documentation](https://github.com/kubernetes-sigs/kubespray/tree/v2.10.4#supported-linux-distributions) that Ubuntu version is supported in `2.10.4` version.

I found that Ritu started that change [here](https://gerrit.onap.org/r/c/multicloud/k8s/+/94484) so maybe you should coordinate these changes with her.

**Comment by electrocucaracha** [comment]
Fixed on 25076e8ac3b14a20b1a214b88e7c48798baabc96
